name: Run Node Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-node-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies in js/
      run: |
        npm install

    - name: Start server in js/ folder
      run: |
        cd js
        npm start
        curl http://localhost:3000 || echo "Server did not respond"
