name: Run Node Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-node-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run server
      run: |
        nohup npm start &
        sleep 5
        curl http://localhost:3000 || echo "Server did not respond"
